[buildpack]
id = "genericlawcoder/heroku-buildpack-apt"
name = "Heroku Buildpack Apt"
version = "2.0.0"

[[apis]]
[[apis.buildpack]]
  deprecated = []
  supported = ["0.2", "0.3", "0.4", "0.5"]
[[apis.platform]]
  deprecated = []
  supported = ["0.3", "0.4", "0.5"]

# For backwards compatibility the minimum supported APIs are provided in RFC-0011 format
# https://github.com/buildpacks/rfcs/blob/main/text/0011-lifecycle-descriptor.md

[[lifecycle]]
  version = "0.16.1"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.focal"
