api = "0.2"

[buildpack]
id = "genericlawcoder/heroku-buildpack-apt"
name = "Heroku Buildpack Apt"
version = "2.1.1"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.focal"
